---
kind: Secret
apiVersion: v1
metadata:
  name: f5demos-registry-secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJmNWRlbW9zLmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiIxZTIxOTkyZS00MjgzLTRhZmUtOWE4OS1iM2IzMTRmMWZkNTUiLCJwYXNzd29yZCI6Ik1lc3pBVGd+VVM2UUd3NUc3Uzc0fjBnWDJreV9YQ2xoSEIiLCJhdXRoIjoiTVdVeU1UazVNbVV0TkRJNE15MDBZV1psTFRsaE9Ea3RZak5pTXpFMFpqRm1aRFUxT2sxbGMzcEJWR2QrVlZNMlVVZDNOVWMzVXpjMGZqQm5XREpyZVY5WVEyeG9TRUk9In19fQ==
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-server-deployment
  labels:
    app: iperf-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf-server
  template:
    metadata:
      labels:
        app: iperf-server
    spec:
      containers:
      - name: iperf-server
        image: f5demos.azurecr.io/iperf
        args: ['-s']
        ports:
        - containerPort: 5201
          name: server
      imagePullSecrets:
      - name: f5demos-registry-secret
      terminationGracePeriodSeconds: 0

---
apiVersion: v1
kind: Service
metadata:
  name: iperf-server
spec:
  selector:
    app: iperf-server
  ports:
  - protocol: TCP
    port: 5201
    targetPort: server
    
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iperf-clients
  labels:
    app: iperf-client
spec:
  selector:
    matchLabels:
      app: iperf-client
  template:
    metadata:
      labels:
        app: iperf-client
    spec:
      containers:
      - name: iperf-client
        image: f5demos.azurecr.io/iperf
        command: ['/bin/sh', '-c', 'sleep infinity']
      imagePullSecrets:
      - name: f5demos-registry-secret
      terminationGracePeriodSeconds: 0
