apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::<account>:role/<NodeInstanceRole>
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::<account>:role/<federated_role_name_that_could_end_with-DO-NOT-DELETE>
      username: ssoadmin:{{SessionName}}
      groups:
      - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::<account>:user/<user>
      username: <user>
      groups:
      - system:masters
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system