---
apiVersion: v1
kind: Config
clusters:
  - name: <cluster-name>
    cluster:      
      certificate-authority-data: <certificate-data>
      server: <server-url>
contexts:
  - name: f5xc-sa@<cluster-name>
    context:      
      cluster: <cluster-name>     
      namespace: kube-system
      user: f5xc-sa
users:  
 - name: f5xc-sa    
   user:      
     token: ****************************
current-context: f5xc-sa@<cluster-name>