---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data: 
  default.conf: |
    log_format main '$http_x_forwarded_for - $remote_user [$time_local] '
      '"$request_method $scheme://$host$request_uri $server_protocol" '
      '$status $body_bytes_sent "$http_referer" '
      '"$http_user_agent" $request_time';

    proxy_connect_timeout 5;
    proxy_send_timeout 5;
    proxy_read_timeout 5;

    server {
        listen 80 default_server;
        access_log /var/log/nginx/access.log main;

        location / {
          proxy_pass http://main/;
        }
        location /files {
          proxy_pass http://backend/files/;
        }
        location /api {
          proxy_pass http://app2/api/;
        }
        location /app3 {
          proxy_pass http://app3/app3/;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: mcn-walkthrough
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - env:
        - name: service_name
          value: backend
        image: registry.gitlab.com/arcadia-application/nginx/nginxoss:latest
        imagePullPolicy: IfNotPresent
        name: proxy
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    app: proxy
    service: proxy
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: proxy